{% set name = "pymatreader" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1bcf0dee93c567701351d83e46b91bf17ea175ac44f3f435fb08e2cfdfbd8534

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-regex-commit
  run:
    - h5py
    - numpy
    - python >={{ python_min }}
    - scipy !=1.7.0
    - xmltodict

test:
  imports:
    - pymatreader
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/obob/pymatreader
  summary: Convenient reader for Matlab mat files
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - thht
    - hoechenberger
