{% set name = "pymatreader" %}
{% set version = "1.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8850b52d735df75b120b6ae5c5f80c92e07d8c163ed653c814d7b904fac7afc5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-regex-commit
  run:
    - h5py
    - numpy
    - python >={{ python_min }}
    - scipy !=1.7.0
    - xmltodict

test:
  imports:
    - pymatreader
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/obob/pymatreader
  summary: Convenient reader for Matlab mat files
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - thht
    - hoechenberger
