{% set name = "pymatreader" %}
{% set version = "1.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d9fee72a8436557273a9ad669de3ed5582782467e2289a131396f575862638ff

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-regex-commit
  run:
    - h5py
    - numpy
    - python >={{ python_min }}
    - scipy !=1.7.0
    - xmltodict

test:
  imports:
    - pymatreader
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://gitlab.com/obob/pymatreader
  summary: Convenient reader for Matlab mat files
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - larsoner
    - thht
    - hoechenberger
